apiVersion: v2
name: mgob
description: |
  A Helm chart for Mgob,  MongoDB dockerized backup agent.
  Runs scheduled backups with retention, S3 & SFTP upload, notifications, instrumentation with Prometheus and more.

type: application

sources:
  - https://github.com/maxisam/mgob

version: 2.1.0

appVersion: "2.0.18"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
# icon: ""
